services:
  backend:
    build:
      context: ./backend/quantity-store-link
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - backend-data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/link
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""

  frontend:
    build:
      context: ./frontend/quantity-count-link
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
